// FIXME: should move hooks to 'src/hooks'
export { useUpdateAppTitle } from './useUpdateAppTitle'
export { useUpdateHtmlLangAttr } from './useUpdateHtmlLangAttr'
export { useSaveAppData } from './useSaveAppData'
export { useLoadExampleCV } from './useLoadExampleCV'
export { useSetAppPropsToState } from './useSetAppPropsToState'
export { useSetCVToState } from './useSetCVToState'
